name: Run Email Bot Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r codeforces-rating-bot/requirements.txt

    - name: Create config.ini
      working-directory: ./codeforces-rating-bot
      run: |
        echo "[EMAIL]" > config.ini
        echo "sender_email = ${{ secrets.SENDER_EMAIL }}" >> config.ini
        echo "password = ${{ secrets.SMTP_PASSWORD }}" >> config.ini
        echo "smtp_server = ${{ secrets.SMTP_SERVER }}" >> config.ini
        echo "smtp_port = ${{ secrets.SMTP_PORT }}" >> config.ini

    - name: Create Google Cloud credentials file
      run: echo '${{ secrets.GCP_SA_KEY }}' > codeforces-rating-bot/service_account.json

    - name: Run python bot
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        cd codeforces-rating-bot
        python3 bot.py
